# Generated by Django 5.1.1 on 2024-09-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blogpost_id_alter_comment_id_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
