# Generated by Django 5.1.1 on 2024-10-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_author_blogpost_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='subtítulo',
            new_name='slug',
        ),
    ]
