# Generated by Django 5.1.1 on 2024-10-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_subtítulo_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='contenido',
            new_name='content',
        ),
    ]
